apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: mongodb-multicontainer-blueprint
  namespace: kasten-io
actions:
  backup:
    outputArtifacts:
      mongoBackup:
        kopiaSnapshot: "{{ .Phases.takeConsistentBackup.Output.kopiaOutput }}"
    phases:
      - func: MultiContainerRun
        name: takeConsistentBackup
        objects:
          mongosecret:
            kind: Secret
            name: '{{ .StatefulSet.Name }}'
            namespace: "{{ .StatefulSet.Namespace }}"
        args:
          namespace: "{{ .StatefulSet.Namespace }}"
          sharedVolumeMedium: Memory

          # --- INIT CONTAINER ---
          initImage: '{{if index .Options "kanisterImage" }}{{- .Options.kanisterImage -}}{{else -}}ghcr.io/kanisterio/kanister-tools:0.116.0{{- end}}'
          initCommand:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              echo "Init container starting MongoDB logical backup test";
              mkfifo /tmp/data;
              chmod 666 /tmp/data

          # --- BACKGROUND CONTAINER (MongoDB dump) ---
          backgroundImage: bitnamilegacy/mongodb:7.0-debian-12
          backgroundCommand:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              host='{{ .StatefulSet.Name }}-0.{{ .StatefulSet.Name }}-headless.{{ .StatefulSet.Namespace }}.svc.cluster.local'
              dbPassword='{{ index .Phases.takeConsistentBackup.Secrets.mongosecret.Data "mongodb-root-password" | toString }}'
              echo "Background container running mongodump";
              dump_cmd="mongodump --oplog --gzip --archive --host ${host} -u root -p ${dbPassword}";
              ${dump_cmd} > /tmp/data

          # --- OUTPUT CONTAINER (push to object storage) ---
          outputImage: '{{if index .Options "kanisterImage" }}{{- .Options.kanisterImage -}}{{else -}}ghcr.io/kanisterio/kanister-tools:0.116.0{{- end}}'
          outputCommand:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              backup_file_path='rs_backup.gz'
              echo "Output container pushing backup to object store";
              cat /tmp/data | kando location push --profile '{{ toJson .Profile }}' --path "${backup_file_path}" --output-name "kopiaOutput" -

  restore:
    inputArtifactNames:
      - mongoBackup
    phases:
      - func: MultiContainerRun
        name: pullFromStore
        objects:
          mongosecret:
            kind: Secret
            name: '{{ .StatefulSet.Name }}'
            namespace: "{{ .StatefulSet.Namespace }}"
        args:
          namespace: "{{ .StatefulSet.Namespace }}"
          sharedVolumeMedium: Memory

          # --- INIT CONTAINER ---
          initImage: '{{if index .Options "kanisterImage" }}{{- .Options.kanisterImage -}}{{else -}}ghcr.io/kanisterio/kanister-tools:0.116.0{{- end}}'
          initCommand:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              echo "Init container preparing restore FIFO";
              mkfifo /tmp/data;
              chmod 666 /tmp/data

          # --- BACKGROUND CONTAINER (pull from store) ---
          backgroundImage: '{{if index .Options "kanisterImage" }}{{- .Options.kanisterImage -}}{{else -}}ghcr.io/kanisterio/kanister-tools:0.116.0{{- end}}'
          backgroundCommand:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              backup_file_path='rs_backup.gz'
              kopia_snap='{{ .ArtifactsIn.mongoBackup.KopiaSnapshot }}'
              echo "Background container pulling backup from object store";
              kando location pull --profile '{{ toJson .Profile }}' --path "${backup_file_path}" --kopia-snapshot "${kopia_snap}" - > /tmp/data

          # --- OUTPUT CONTAINER (restore to MongoDB) ---
          outputImage: bitnamilegacy/mongodb:7.0-debian-12
          outputCommand:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              host='{{ .StatefulSet.Name }}-0.{{ .StatefulSet.Name }}-headless.{{ .StatefulSet.Namespace }}.svc.cluster.local'
              dbPassword='{{ index .Phases.pullFromStore.Secrets.mongosecret.Data "mongodb-root-password" | toString }}'
              echo "Output container restoring MongoDB data";
              restore_cmd="mongorestore --gzip --archive --oplogReplay --drop --host ${host} -u root -p ${dbPassword}";
              cat /tmp/data | ${restore_cmd}

  delete:
    inputArtifactNames:
      - mongoBackup
    phases:
      - func: KubeTask
        name: deleteFromStore
        args:
          namespace: "{{ .Namespace.Name }}"
          image: '{{if index .Options "kanisterImage" }}{{- .Options.kanisterImage -}}{{else -}}ghcr.io/kanisterio/kanister-tools:0.116.0{{- end}}'
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              backup_file_path='rs_backup.gz'
              kopia_snap='{{ .ArtifactsIn.mongoBackup.KopiaSnapshot }}'
              echo "Deleting MongoDB backup from object store";
              kando location delete --profile '{{ toJson .Profile }}' --path "${backup_file_path}" --kopia-snapshot "${kopia_snap}"